### ISSUE TITLE
Hamburger menu broken on mobile.

### ISSUE THREAD

**Issue by Collinthegeek** [papyros/papyros.github.io#32]
For me (Moto X 2013, chrome) the hamburger menu doesn't work.

**Comment by AlvaroOrduna** [comment]
Happens the same to me. Android 5.1 (Nexus 4) with Chrome 42.0

**Comment by Vogeltak** [comment]
This is solved in my [submitted pull request](https://github.com/papyros/papyros.github.io/pull/34).
