### ISSUE TITLE
Links broken on developer page.

### ISSUE THREAD

**Issue by Collinthegeek** [papyros/papyros.github.io#33]
On the developer page (http://papyros.io/developer/) the links are broken on mobile and possibly desktop. Screenshot: 

![screenshot_2015-05-06-20-42-10](https://cloud.githubusercontent.com/assets/3230912/7507237/7e38637e-f432-11e4-9965-ec65d87db380.png)

**Comment by Vogeltak** [comment]
Is this about the funky layout of the buttons? Then I have a fix for that. I however don't experience a broken link on desktop/mobile.
