### ISSUE TITLE
Mobile design 

### ISSUE THREAD

**Issue by Schwertspize** [papyros/papyros.github.io#38]
first: your mobile design is great!
second: *please* add a better navigation at bottom. eg your blog is unreachable on mobile...

**Comment by hakarune** [comment]
can you be more specific. Isn't the blog link in the slide-out nav panel? I don't see it at the bottom.

**Comment by Schwertspize** [comment]
yes, sorry.... i was talking about the front page.....  papyros/papyros.github.io#16



![screenshot1](https://cloud.githubusercontent.com/assets/11271600/8588692/b3bdcc34-260d-11e5-8b11-34a427081567.png)
![screenshot2](https://cloud.githubusercontent.com/assets/11271600/8588696/b9de20a0-260d-11e5-8774-9ef28151f9f5.png)
![screenshot3](https://cloud.githubusercontent.com/assets/11271600/8588699/c122627c-260d-11e5-8311-2dcd21122d45.png)
![screenshot4](https://cloud.githubusercontent.com/assets/11271600/8588702/c674adf2-260d-11e5-9dc8-19b2653141b7.png)
