### ISSUE TITLE
Redesign the project page with material

### ISSUE THREAD

**Issue by DavidAwad** [papyros/papyros.github.io#5]
You may want to use the polymer project's material design web components to really pull off the material design. I tried to do it for you but getting web components to work on Ubuntu is a pain in the neck.

https://www.polymer-project.org/components/paper-elements/demo.html#paper-icon-button

**Comment by iBeliever** [comment]
@DavidAwad Any progress on this? I've had two other offers to work on a Material Design version of our website, so if you don't have time to work on this anymore, I can ask them to tackle it.

**Comment by DavidAwad** [comment]
sincerely i apologize i tried to make the time but it just never got any easier. Hope it goes well and i'll try to continue in another way!!

**Comment by jgw96** [comment]
I can build the site for you using Polymer? I've used Polymer extensively in my own work.

**Comment by VirusKA** [comment]
I guess since no one else is doing it.

**Comment by iBeliever** [comment]
@jgw96 I have two other people who said they would work on it. Let me check with them first and see what the status is. If they're not working on it, that would be great to have you help!

**Comment by jgw96** [comment]
Sounds good to me! I will be waiting to hear from you !

**Comment by VirusKA** [comment]
I have been trying to redesign this, and it looks like we might have to move the blog stuff to something like papyros.io/blog/ and make the actual site on here.

**Comment by iBeliever** [comment]
Closing now as we have a nice material design style using the Materialize CSS framework.
