### ISSUE TITLE
Please add an IRC channel for development

### ISSUE THREAD

**Issue by pksunkara** [papyros/papyros.github.io#6]
So that people like me can chat with you.

**Comment by tvvocold** [comment]
+1
and a mailing list such like google group.

**Comment by tvvocold** [comment]
@iBeliever

**Comment by iBeliever** [comment]
Ok, our IRC channel is set up at `#papyros` on Freenode. I'm `iBelieve` on IRC, and I have a bouncer set up so if I'm not online I should be able to see messages once I come online.

 We also now have a Google Group at https://groups.google.com/forum/#!forum/papyros.

I'll leave this open until I can post this info on Google+ and list it on our website.

**Comment by tvvocold** [comment]
@iBeliever 
I think it's better to sign up twitter/fb account for release news, etc.
(and you can use [ifttt.com](https://ifttt.com/recipes/128796-rss-feed-to-facebook) for sync)

**Comment by iBeliever** [comment]
The [Support](http://papyros.io/support/) page on our website now has different support/communication options, including IRC and a mailing list.

@tvvocold I don't/won't use Facebook for various reasons. I don't really want to use Twitter, as that's one more channel I would need to use and monitor, but I'll think about it, especially with automatic posting.

**Comment by tvvocold** [comment]
@iBeliever 
OK.
BTW, if you wanna donate (i saw a donate button in your home page),  it's better to use paypal or [stripe](https://stripe.com/) , there's no secure at all to transfer visa info via http( without ssl).
See https://github.com/papyros/papyros.github.io/issues/29
